---
output: github_document
---

# xaringan_slides

Links to HTML5 presentations made using the R package [**{xaringan}**](https://github.com/yihui/xaringan/). 

## Presentations

+ [Setting up your PhD (or other research project!) as an R package by Ella Kaye](https://htmlpreview.github.io/?https://raw.githubusercontent.com/r-oxford/r-oxford.github.io/master/slides/2018_04_PhD_to_package.html)

+ [Is the Parkland Event Different? Using R to Investigate the Persistence of Public Interest in Mass Shooting Events by Ben Marwick](https://rawgit.com/benmarwick/Seattle-UseR-Group-April-2018/master/Seattle-UseR-Group-April-2018.html)

+ [Power Analysis for Longitudinal 2- and 3-Level Models Challenges and Some Solutions Using the R Package powerlmm by Kristoffer Magnusson](http://rpsychologist.com/slides/powerlmm-intro-20180411/)

+ [Political Information, New Media, and Twitter bots by Michael W. Kearney](https://mkearney.github.io/dsa_execweek_talk/)

+ [Statistical Inference: A Tidy Approach by Dr. Chester Ismay](https://ismayc.github.io/talks/ness-infer/slide_deck.html)

+ [Exploring and Visualizing School Achievement and School Effects by Daniel Anderson](http://www.dandersondata.com/talks/ncme18/)

+ [Visualizing GeoData with R: Introduction to sf & tmap by Thomas Lo Russo & Max Grütter](https://tlorusso.github.io/geodata_workshop/)

+ [R: Collecting and Analyzing Twitter Data featuring {rtweet} by Michael W. Kearney](https://mkearney.github.io/nicar_tworkshop/)

+ [R-Ladies Presentation Ninja with xaringan by Alison Presmanes Hill](https://alison.rbind.io/slides/rladies-demo-slides.html)

+ [Take A Sad Plot & Make It Better: A Case Study with R and ggplot2 by Alison Presmanes Hill](https://apreshill.github.io/ohsu-biodatavis/slides.html)

+ [Presentation Ninja with xaringan by Yihui Xie](https://slides.yihui.name/xaringan/)

+ [Steve's Xaringan Presentation: POSC 0000 – It Would Be Cool If This Were an Actual Class Presentation by Steven V. Miller](http://svmiller.com/miscellany/svm-xaringan-example.html)

+ []()

+ []()

+ []()

+ []()

+ []()

+ []()

+ []()

+ []()

+ []()

+ []()

## About {xaringan}

+ [Why xaringan / remark.js for HTML5 Presentations? by Yihui Xie](https://yihui.name/en/2017/08/why-xaringan-remark-js/)

+ [A Twist of Hygge in xaringan by Yihui Xie](https://yihui.name/en/2018/02/xaringan-hygge/)

+ [Make Your Presentations Fun in Xaringan by Steven V. Miller](http://svmiller.com/blog/2018/02/r-markdown-xaringan-theme/)
